### ISSUE TITLE
How to get 2D keypoints from VIBE wrt to orig cam parameters?

### ISSUE THREAD

**Issue by cbsudux** [mkocabas/VIBE#100]
For getting 2D pose from pred_cam in cropped image space you have the below code where you take `tx` and `ty` and add the third dimension as this `2 * 5000. / (224. * pred_camera[:, 0] + 1e-9)]` where `244` is the crop size. 

https://github.com/mkocabas/VIBE/blob/945fd109eaace037b38c56e22ec235a9d3c5100a/lib/models/spin.py#L427-L429

How do I adapt `2 * 5000. / (224. * pred_camera[:, 0] + 1e-9)]` to the full image where width and height are different?  I'm assuming the crops are `244x244` and `pred_camera[:, 0]` is the pred camera scale which is just `s`, whereas `orig_cam` has for both axes `sx` and `sy` and has `orig_cam[:, 0]` and `orig_cam[:, 1]`.

**Comment by mkocabas** [comment]
Hi @cbsudux,

Instead of playing with the perspective projection, you can take the predicted `joints2d` which are on the cropped image space and convert them into original image space using the bbox coordinates. This way might be easier than the perspective projection.

**Comment by mkocabas** [comment]
Closing the issue due to inactivity, feel free to reopen it if needed.

**Comment by antoinedelplace** [comment]
Hi @cbsudux,

Have you succeeded in projecting the 3D joints in the 2D original camera plane ?

Thank you for any help !

**Comment by cbsudux** [comment]
No, didn't work. The 2D keypoints are skewed. Better to use a quick 2d estimator
