### ISSUE TITLE
set the "--tracking_method == pose",

### ISSUE THREAD

**Issue by runningpp** [mkocabas/VIBE#104]
Hi, In the code, the default of "tracking_method" is "bbox", if I choose "pose", it didn't run successfully, cause lack of the STAF model of body_21A.
How could I get the model?

**Comment by aingo03304** [comment]
I just changed the default argument in the lib/utils/pose_tracker from "BODY_21A" to "BODY_25".

**Comment by aingo03304** [comment]
https://github.com/mkocabas/VIBE/issues/30

**Comment by mkocabas** [comment]
Thanks @aingo03304 for the fix!
