### ISSUE TITLE
full_pose in smplify

### ISSUE THREAD

**Issue by ikvision** [mkocabas/VIBE#107]
In the last stage of simplify:
https://github.com/mkocabas/VIBE/blob/2ba005c0f2d5e42c15bc8057ab7ad5584192d717/lib/smplify/temporal_smplify.py#L186-L188
`return_full_pose` is set to True, while `full_pose` generated  output doesn't seem to be used.
I think that setting  `full_pose` to False may reduce the run time of simplify

Can you elaborate on the need for `full_pose`

**Comment by mkocabas** [comment]
Thanks @ikvision, I fixed it.
