### ISSUE TITLE
Error occur when Install the requirements using conda

### ISSUE THREAD

**Issue by christw16** [mkocabas/VIBE#108]
Hi ~
after I clone the repo, and choose to use conda option
running "source scripts/install_conda.sh"

it shows some error.
Could you help me to find out the error?
Thank you~

================================================================
 Cloning https://github.com/mattloper/chumpy.git to /tmp/pip-req-build-dehgc98i
  Running command git clone -q https://github.com/mattloper/chumpy.git /tmp/pip-req-build-dehgc98i
    ERROR: Command errored out with exit status 1:
     command: /home/iis/.conda/envs/vibe-env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dehgc98i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dehgc98i/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5884mcaq
         cwd: /tmp/pip-req-build-dehgc98i/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dehgc98i/setup.py", line 15, in <module>
        install_requires = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-req-build-dehgc98i/setup.py", line 15, in <listcomp>
        install_requires = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by christw16** [comment]
I see the problem.
If pip version is 20 or the latest, it will have error above
pip version with 19 will not face this error

**Comment by mkocabas** [comment]
Seems like the issue is solved.
