### ISSUE TITLE
How can I use 3d pose

### ISSUE THREAD

**Issue by zhhaochen** [mkocabas/VIBE#11]
Hi, thank you for your amazing work, I have try it and get perfect video and vibe_output.pkl file. I don't know much about 3d mesh. Can you tell me what are saved in the file? Can I get 3d pose from it? Look forward to your reply.

**Comment by mkocabas** [comment]
Hi @zhhaochen,

Thanks for your interest.

pkl content is described here: [demo.md#output-format](https://github.com/mkocabas/VIBE/blob/master/doc/demo.md#output-format). It is very easy to append 3D pose to output file. I will add and update here.

**Comment by mkocabas** [comment]
Added. Check this commit: https://github.com/mkocabas/VIBE/commit/55cf6d606290f0a66554597cc6c0a164d50147a7

**Comment by zhhaochen** [comment]
> Added. Check this commit: [55cf6d6](https://github.com/mkocabas/VIBE/commit/55cf6d606290f0a66554597cc6c0a164d50147a7)

Thanks for your perfect work!!!
