### ISSUE TITLE
Something wrong with get_coco_joint_names() and get_3dpw_joint_names() [BUG]

### ISSUE THREAD

**Issue by donghaoye** [mkocabas/VIBE#110]
the order of get_coco_joint_names is wrong.

**Comment by mkocabas** [comment]
Hi @donghaoye,

I double checked it, there is no mistake.

**Comment by donghaoye** [comment]
@mkocabas Hi, according to the 3dpw descriptions of the readme of 3dpw, the 2D joint detections in Coco-Format for each actor.  I think the below order is right.


def get_coco_joint_names():
    return [
        "nose",      # 0
        "neck",       # 1
        "lshoulder",       # 2
        "lelbow",       # 3
        "lwrist",       # 4
        "rshoulder",       # 5
        "relbow",      # 6
        "rwrist",       # 7
        "lhip",       # 8
        "lknee",       # 9
        "lankle",       # 10
        "rhip",       # 11
        "rknee",       # 12
        "rankle",       # 13
        "leye",       # 14
        "reye",       # 15
        "lear",       # 16
        "rear",       # 17
    ]
