### ISSUE TITLE
retrieve AMASS translation from VIBE prediction

### ISSUE THREAD

**Issue by HenriMir** [mkocabas/VIBE#111]
Hello, thanks for the amazing work from you and the lab!

I have a question regarding your architecture that is more a lack of understanding on my side.
I can see that your architecture predicts beta, theta from the smpl model and cam

beta and theta, to my understanding of the smpl model, allows to recreate the body shape and pose at one specific frame, but with a fixed root joint. 
But we can see on your demo that your model supports the movement in space and not only the movement in pose.

So here is my question : how is it possible to retrieve the movement in space (which should be a (n_frames, 3) vector, corresponding to the "trans" vector present in AMASS dataset) based on pose and cam ? 

Apologies if my question is not clear!
Thanks for any lead on that!

**Comment by mkocabas** [comment]
Hi @HenriMir,

Recovering global transformation from SMPL parameters and estimated weak perspective camera is non-trivial. We do not tackle it in this project.

AMASS uses motion capture datasets which is collected using calibrated camera setups. Known camera setup makes it possible to recover global position.

**Comment by HenriMir** [comment]
thank you for your answer.
This data might be useful for the issue https://github.com/mkocabas/VIBE/issues/1

First lead I see there, but that might be overkill, would be to use AMASS to predict this "trans" vector using the GAN you already trained on AMASS data and the cam data outputted by your model. 

I'll update here if I make any breakthrough on this "nontrivial" problem.

**Comment by mayank64ce** [comment]
@HenriMir did you find a way to get `translation` parameters for a particular `vibe_output.pkl`  ?

and @mkocabas if say I know where the camera is, how can I get the `trans` parameters for that actor ?
