### ISSUE TITLE
[FEATURE]H36m mosh data

### ISSUE THREAD

**Issue by JackSyu** [mkocabas/VIBE#112]
**Is your feature request related to a problem? Please describe.**
Hi, could you please provide the mosh data of h36m? Thank you very much!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mkocabas** [comment]
Hi @JackSyu,

Unfortunately, we are not allowed to release Human3.6M mosh fittings.
