### ISSUE TITLE
Output without overlap on the original video 

### ISSUE THREAD

**Issue by gayatriprasad** [mkocabas/VIBE#121]
Hello. 

Is it possible to save just the output/prediction and not the the output/prediction overlapped with the original video ? I see it is possible to save the side view, however, it's together with the overlapped prediction. 

Thanks

**Comment by mkocabas** [comment]
Hi @gayatriprasad,

You would need to give all zeros input to the renderer. Just change this line https://github.com/mkocabas/VIBE/blob/master/demo.py#L294 to np.zeros_like(img).

**Comment by gayatriprasad** [comment]
Thanks for the quick reply.
