### ISSUE TITLE
Difference 'cam' parameter between HMR and VIBE

### ISSUE THREAD

**Issue by AmberCheng** [mkocabas/VIBE#122]
Thanks for your wonderful work~
I have met something confused. As we know, VIBE can get the parameters as HMR. But when I use the VIBE to replace the HMR and get SMPL data, the SMPL person I rendered is rotating up and down. I wonder is there some differences in the cams params between HMR and VIBE.

**Comment by mkocabas** [comment]
Hi @AmberCheng,

The estimated camera parameters of VIBE and HMR are technically the same weak perspective camera parameters. However, the renderer we use is different than HMR so it is expected to have this rotation issue. A fixed amount of rotation should solve your issue.

**Comment by AmberCheng** [comment]
> Hi @AmberCheng,
> 
> The estimated camera parameters of VIBE and HMR are technically the same weak perspective camera parameters. However, the renderer we use is different than HMR so it is expected to have this rotation issue. A fixed amount of global rotation should solve your issue.

@mkocabas Sorry to bother. But when I use HMR, I actually get 3 camera parameters while VIBE gives me 4 parameters of origin camera.  I want to use neural_renderer(https://github.com/hiroharu-kato/neural_renderer) to render the VIBE pkl file. How should I  deal with the camera parameter?

**Comment by antoinedelplace** [comment]
Hi @AmberCheng,

I am also confused about this : why the origin camera have 4 parameters (two for x and two for y) and not 3 parameters corresponding to x, y and z axis ?

Have you figured it out ? If yes, can you share please ?

**Comment by ovshake** [comment]
@antoinedelplace hi, I am facing the same issue. Have you figured this out? 
Thanks
