### ISSUE TITLE
The foot joint?

### ISSUE THREAD

**Issue by forevertsyj** [mkocabas/VIBE#123]
Hello,
Thank you for the excellent work!

I noticed in the demo, there was pose of foot. But in get_spin_joint_names(), there is no left_foot or right_foot. In MPII_3D there are these two joints. How to acquire the foot joints, from the 49 joints?

Thanks.

**Comment by athn-nik** [comment]
Hi @forevertsyj ! There is left and right ankle , heel and toe in spin_names https://github.com/mkocabas/VIBE/blob/fda0950d639be8d8847e4d91af7ebde465638bd7/lib/data_utils/kp_utils.py#L212
Which joint do you want?
You can find their mapping and relevant names here https://github.com/mkocabas/VIBE/blob/fda0950d639be8d8847e4d91af7ebde465638bd7/lib/models/smpl.py#L14

**Comment by forevertsyj** [comment]
Got it. Thanks!
