### ISSUE TITLE
[FEATURE] How to denose the body pose shaking

### ISSUE THREAD

**Issue by acupofespresso** [mkocabas/VIBE#125]
The body model rendered in sample video is shaking, how to denose it.

**Comment by ikvision** [comment]
The authors of this paper https://arxiv.org/abs/2009.06549 used a OneEuro Filter in the time domain, as post processing which seem to get some nice gains in performance 
![image](https://user-images.githubusercontent.com/11877852/94089898-2341f380-fdc9-11ea-9f92-42864c964695.png)

**Comment by acupofespresso** [comment]
I will try it.

Thanks a lot!

**Comment by mkocabas** [comment]
Demo supports OneEuroFilter now. Pass `--smooth` flag to the demo script.
