### ISSUE TITLE
How did you train the discriminator? 

### ISSUE THREAD

**Issue by OOF-dura** [mkocabas/VIBE#126]
I want to know how did you train the discriminator?  Seems like the paper did not give too many details.
And which dataset are you using for training discriminator? 

It is easy to get positive samples, but how can you get the negative(bad motion) samples?

Thank you!

**Comment by ikvision** [comment]
The discriminator tries to differentiate between real world examples (AMASS captured motion sequences) and the generated examples (output from VIBE).  
As the training progresses, the generated examples should become similar to the real world examples and the discriminator should not be able to differentiate between the two sets.

**Comment by mkocabas** [comment]
Thanks @ikvision for the reply. That is correct and this is explained in the paper.
