### ISSUE TITLE
Hi, I really appreciate your work.  I have a  question about SMPLX.  From my understanding, VIBE uses AMASS to train its pose discriminator.  However AMASS does not handle SMPLX,  is there a way for VIBE to combine both AMASS and SMPLX in order to train the pose discriminator?  

### ISSUE THREAD

**Issue by heidi-zhenhai** [mkocabas/VIBE#129]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by heidi-zhenhai** [comment]
Hi,

Thank you very much for your excellent work.  I have a question related to SMPLX.  From the paper, VIBE uses AMASS dataset to train the pose discriminator.  I am just wondering: can we train the pose discriminator with both AMASS and SMPLX together?  

Thank you very much,
Heidi

**Comment by heidi-zhenhai** [comment]
Hi, 

What a great job.   The paper says that VIBE uses AMASS to train the discriminator.  Can we train the discriminator by both AMASS and SMPLX so that we can show facial expression better?  Thanks!

Heidi

**Comment by ikvision** [comment]
I think that extending VIBE to use SMPLX was requested few time eg. https://github.com/mkocabas/VIBE/issues/117 or https://github.com/mkocabas/VIBE/issues/65
Maybe https://github.com/vchoutas/expose is a better starting point

**Comment by mkocabas** [comment]
Hi @heidi-zhenhai,

Extending VIBE to work with SMPLX requires non-trivial changes. You can refer to ExPose as @ikvision mentioned.
