### ISSUE TITLE
How to get a mean shape?

### ISSUE THREAD

**Issue by forevertsyj** [mkocabas/VIBE#130]
Hi, 
Thanks for the wonderful work!

I noticed that VIBE predicted beta (shape) for each frame of the same person. How to get a mean shape of the person, just average the betas of each frame? For example, I want to get the mean shape of a human from a video sequence, which should be more accurate than estimating from single frame?

Looking forward to hearing from you!

**Comment by mkocabas** [comment]
Hi @forevertsyj,

You can try taking the mean or median of betas. Median may be more robust to outliers.

**Comment by HospitableHost** [comment]
> Hi @forevertsyj,
> 
> You can try taking the mean or median of betas. Median may be more robust to outliers.

Hi, I noticed that the paper said that "Specifically, for each frame we predict the body shape parameters. Then, we apply average pooling to get a single shape (β) across the whole input sequence."
But I can't find any code to do such thing in your code. Where am I missed ?
