### ISSUE TITLE
[Question] Is it possible to find the position (including depth) of a person's root in global coordinates?

### ISSUE THREAD

**Issue by miu200521358** [mkocabas/VIBE#133]
Hi. I am very impressed with this wonderful work.

> Unfortunately, VIBE predicts root relative pose only.  https://github.com/mkocabas/VIBE/issues/18

After reading the issue above, I understand that the position of each joint is relative.
Then, is it possible to find the global coordinates (including depth) of the root with VIBE?
I tried to find the global coordinates using orig_cam and joints3d, but it didn't work.
You can just use methods, formulas or hints, so if you know anything, please let me know.
Thank you.

**Comment by ikvision** [comment]
VIBE as well as SPIN assumes weak perspective which as I understand it may create large error in the depth estimation as it used unrealistically large focal length. Copied from https://arxiv.org/abs/2009.06549
The authors of SPIN (and VIBE)
"have chosen the weak perspective camera model in the projection procedure. Thus, it is assumed that the camera is far from the person. This assumption is realized by using unrealistically large focal length."

**Comment by miu200521358** [comment]
Thank you for your response!

I understand that there will be an error in the depth.
Then, is it difficult to obtain the vertical and horizontal positions on the screen plane with VIBE?
Is it safe to assume that the values that can be referenced from bbox indicate the position within the size range of the video?

I'm sorry for your inconvenience but thank you for your cooperation.

**Comment by ikvision** [comment]
The joint locations are indeed relative to the cropped bounding box. 
Calculating the global position from relative position description and code are in https://github.com/ikvision/ikvision.github.io/blob/master/README.md#4-calculate-joints-3d-location 
It is the accumulation of relative rotations according to the kinematic tree

**Comment by miu200521358** [comment]
Thank you for your response!
I will study while looking at the article you wrote.

Good luck and more power!
