### ISSUE TITLE
Why use 49 key points, these 49 key points have many repetitive points[FEATURE]

### ISSUE THREAD

**Issue by ysp568** [mkocabas/VIBE#146]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mkocabas** [comment]
@ysp568 as you will see here: https://github.com/mkocabas/VIBE/blob/master/lib/data_utils/kp_utils.py#L212 first 25 keypoints are compatible with openpose keypoints. Those are used to fit SMPL to openpose predicted keypoints.
