### ISSUE TITLE
about the visualization of the "joints3d"

### ISSUE THREAD

**Issue by elk-april** [mkocabas/VIBE#164]
Hello, is there something wrong with this code?  
```
for i in range(output["frame_ids"].shape[0]):
    img_name = os.path.join(imgs, image_file_names[i])

    img = cv2.imread(img_name)
    pred_j3ds = output["joints3d"][i, :, :]
    pred_cam = output["pred_cam"][i, :]
    verts = output["verts"][i,:, :]
    bbox = output["bboxes"][i, :]

    ratio = 1.0 / 224.0
    kp_2d = (pred_j3ds[:, :2] + 1.0) / (2 * ratio)

    kp_2d = transfrom_keypoints(
        kp_2d, bbox[0], bbox[1], bbox[2], bbox[3], 224, 224, False
    )[0]

    for idx in range(49):
        cv2.circle(img, (int(kp_2d[idx][0]), int(kp_2d[idx][1])), 5, (255, 0, 0), -1)
``` 
My visualization is going to be skewed like below:
![image](https://user-images.githubusercontent.com/22853879/102197590-52fe2480-3efc-11eb-9765-24212eb9ebcd.png)

**Comment by elk-april** [comment]
and I try this:
```
    ratio = 1.0 / 224.0
    kp_2d = (pred_j3ds[:, :2] + 1.0) / (2 * ratio)

    kp_2d[:, 0] = kp_2d[:, 0] / 224 * bbox[3] + bbox[0] - bbox[3] / 2 
    kp_2d[:, 1] = kp_2d[:, 1] / 224 * bbox[2] + bbox[1] - bbox[2] / 2 
```
![image](https://user-images.githubusercontent.com/22853879/102213687-11787400-3f12-11eb-8070-a91644021220.png)

**Comment by arpitmac74** [comment]
hey can you show the function transfrom_keypoints?

**Comment by arpitmac74** [comment]
kp_2d = points[:,:3]
kp_2d[:,0] = ((kp_2d[:, 0] +1 ) / (2 * ratio1 )*s1)  + box[0] - (box[3]/2)     ## scling is correct translation have to figure out 
kp_2d[:,1] = ((kp_2d[:, 1] +1 ) / (2 * ratio2 )*s2)  + box[1] - (box[2]/2)

This works
