### ISSUE TITLE
Temporal SMPLify Option Error

### ISSUE THREAD

**Issue by Hwang-dae-won** [mkocabas/VIBE#17]
Hi,
Thank you for your awesome work.

I have a problem with Temporal SMPLify Option.

I installed VIBE and Openpose with STAF.

When I execute command like this

`python demo.py --vid_file sample_video.mp4 --output_folder output/ --tracking_method pose --display --staf_dir /home/user/1.Code/openpose_STAF --run_smplify`

I got this error

> Error:
> Cuda check failed (77 vs. 0): an illegal memory access was encountered
> 
> Coming from:
> - /home/user/1.Code/openpose_STAF/src/openpose/pose/poseExtractorNet.cpp:getHeatMapsCopy():228
> - /home/user/1.Code/openpose_STAF/src/openpose/gpu/cuda.cpp:cudaCheck():42
> - /home/user/1.Code/openpose_STAF/src/openpose/pose/poseExtractorNet.cpp:getHeatMapsCopy():234
> - /home/user/1.Code/openpose_STAF/src/openpose/pose/poseExtractor.cpp:getHeatMapsCopy():65
> - /home/user/1.Code/openpose_STAF/include/openpose/pose/wPoseExtractor.hpp:work():108
> - /home/user/1.Code/openpose_STAF/include/openpose/thread/worker.hpp:checkAndWork():93
> 
> Error:
> Cuda check failed (77 vs. 0): an illegal memory access was encountered
> 
> Coming from:
> - /home/user/1.Code/openpose_STAF/src/openpose/net/nmsBase.cu:nmsGpu():345
> - /home/user/1.Code/openpose_STAF/src/openpose/gpu/cuda.cpp:cudaCheck():42
> - /home/user/1.Code/openpose_STAF/src/openpose/net/nmsBase.cu:nmsGpu():349
> - /home/user/1.Code/openpose_STAF/src/openpose/net/nmsCaffe.cpp:Forward_gpu():240
> - /home/user/1.Code/openpose_STAF/src/openpose/net/nmsCaffe.cpp:Forward():200
> - /home/user/1.Code/openpose_STAF/src/openpose/pose/poseExtractorCaffeStaf.cpp:forwardPass():411
> - /home/user/1.Code/openpose_STAF/src/openpose/pose/poseExtractor.cpp:forwardPass():53
> - /home/user/1.Code/openpose_STAF/include/openpose/pose/wPoseExtractor.hpp:work():108
> - /home/user/1.Code/openpose_STAF/include/openpose/thread/worker.hpp:checkAndWork():93
> F0107 11:18:46.491232 17293 syncedmem.hpp:22] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
> *** Check failure stack trace: ***
> F0107 11:18:46.491261 17294 math_functions.hpp:179] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
> *** Check failure stack trace: ***
>     @     0x7f7d02e960cd  google::LogMessage::Fail()
>     @     0x7f7d02e97f33  google::LogMessage::SendToLog()
>     @     0x7f7d02e95c28  google::LogMessage::Flush()
>     @     0x7f7d02e960cd  google::LogMessage::Fail()
>     @     0x7f7d02e98999  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f7d0235c853  caffe::SyncedMemory::mutable_cpu_data()
>     @     0x7f7d02368c95  caffe::Blob<>::Reshape()
>     @     0x7f7d023690ca  caffe::Blob<>::Reshape()
>     @     0x7f7d02e97f33  google::LogMessage::SendToLog()
>     @     0x7f7d0236917c  caffe::Blob<>::Blob()
>     @     0x7f7d048378cf  op::ArrayCpuGpu<>::ArrayCpuGpu()
>     @     0x7f7d02e95c28  google::LogMessage::Flush()
>     @     0x7f7d049232b5  op::PoseExtractorCaffeStaf::netInitializationOnThread()
>     @     0x7f7d04932853  op::PoseExtractorNet::initializationOnThread()
>     @     0x7f7d02e98999  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f7d04914d21  op::PoseExtractor::initializationOnThread()
>     @     0x7f7d0490f7c1  op::WPoseExtractor<>::initializationOnThread()
>     @     0x7f7d0235bfca  caffe::SyncedMemory::mutable_gpu_data()
>     @     0x7f7d049754c1  op::Worker<>::initializationOnThreadNoException()
>     @     0x7f7d0235e0d2  caffe::Blob<>::mutable_gpu_data()
>     @     0x7f7d049755f0  op::SubThread<>::initializationOnThread()
>     @     0x7f7d04977948  op::Thread<>::initializationOnThread()
>     @     0x7f7d02538590  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
>     @     0x7f7d04977b17  op::Thread<>::threadFunction()
>     @     0x7f7d0236ff72  caffe::Net<>::ForwardFromTo()
>     @     0x7f7d03dac66f  (unknown)
>     @     0x7f7d034ce6db  start_thread
>     @     0x7f7d048f3215  op::NetCaffe::forwardPass()
>     @     0x7f7d0380788f  clone

So, I execute simple command like this on Openpose_STAF folder
`./build/examples/openpose/openpose.bin --video examples/media/video.avi`
It works well

But, when i run the command as your code(pose_tracker.py)

` ./build/examples/openpose/openpose.bin --video examples/media/video.avi --model_pose BODY_21A --tracking 1 --render_pose 1 --display 2`

I got same error.
How can i solve this?

This is my Computer Environment.
- Cuda:10.0, CuDNN:7.5.0, GTX2080TI x 4 

As an additional question, Does STAF mean Spatio-Temporal-Affiny-Field?

**Comment by mkocabas** [comment]
Hi @Hwang-dae-won,

Thanks for your interest. It seems after you clone the STAF openpose you didn't checkout `staf` branch. You should compile it from [`staf`](https://github.com/soulslicer/openpose/tree/staf) branch.

> As an additional question, Does STAF mean Spatio-Temporal-Affiny-Field?

Yes, it is the implementation of [this paper](https://arxiv.org/abs/1811.11975).

**Comment by Hwang-dae-won** [comment]
I confirmed that this is not an issue with the branch. 

If you are using multiple gpu like me, you can run it with --num_gpu 1 option. 

I guess there is a problem with the openpose_STAF code.
