### ISSUE TITLE
Modeling a sequence of images

### ISSUE THREAD

**Issue by ikvision** [mkocabas/VIBE#19]
If I understand correctly the HMR is initialized from mean_pose for each frame of the video:
[https://github.com/mkocabas/VIBE/blob/master/lib/models/spin.py#L196](url)

Did you try to initialize each frame prediction from the previously predicted pose?

**Comment by mkocabas** [comment]
No, we didn't try it. But I think it is a good idea to train the recurrent model in an autoregressive manner.
