### ISSUE TITLE
2D joints from STAF output format

### ISSUE THREAD

**Issue by kallivad** [mkocabas/VIBE#20]
Hi @mkocabas, great thanks for your great work!
My question is about STAF tracker output format.
According to https://github.com/mkocabas/VIBE/blob/master/doc/demo.md#runtime-performance
we get:
joints2d (n_frames, 21, 3)  # 2D keypoint detections by STAF if pose tracking enabled otherwise None

21 is the number of joints
but what is the last 3? as far as i can understand from STAF repo it have to contain x,y coords from original frame, but what it really contains?

**Comment by mkocabas** [comment]
STAF predicts x, y and confidence scores for each keypoint. So, 3rd dimension corresponds to confidence of each prediction.
