### ISSUE TITLE
How can I get results like header_1.gif ？

### ISSUE THREAD

**Issue by zr2020-stu** [mkocabas/VIBE#209]
![image](https://user-images.githubusercontent.com/75256462/127321854-fef7798f-b010-4890-876f-7d5995eddb6b.png)
Help!!! How can I get results like header_1.gif  and header_2.gif. Just show Vertex data instead of mesh data。

**Comment by mkocabas** [comment]
You need to pass `--wireframe` argument to the `demo.py` script.
