### ISSUE TITLE
[FEATURE]Joints Visualization

### ISSUE THREAD

**Issue by Tyushang** [mkocabas/VIBE#217]
There's many joint regressor in the project, e.g. J_regressor_extra / J_regressor_h36m , but I can not find out where those joints locate in the human-body. so could you visualize it?

**Comment by athn-nik** [comment]
you could use code from here https://github.com/mkocabas/VIBE/blob/03ed50d3121c37a4abfcc25dc995f08b63fd7f1f/lib/utils/vis.py#L219 . This function could be used to visualize skeleton in addition.
