### ISSUE TITLE
[BUG]CPU without GPU

### ISSUE THREAD

**Issue by zhangchengzhi-max** [mkocabas/VIBE#219]
The last step is this error. My computer has no GPU. According to this prompt, I don't know where to change the code. Please help. Thank you
![132863565-4868ff14-1d2c-4286-8061-ac231edd3270](https://user-images.githubusercontent.com/63695075/132932729-8bd35bf4-db42-464f-94d6-62078d3955e7.png)

**Comment by liuhaorandezhanghao** [comment]
device改成device=torch.device('cpu'),还有ckpt = torch.load(pretrained_file,map_location='cpu')
