### ISSUE TITLE
Choosing a custom color for person ID and background

### ISSUE THREAD

**Issue by AndroYD84** [mkocabas/VIBE#23]
Is there a simple way to modify the code so I can assign a custom color to each person ID number instead of having it randomized? Such as "0: Green" "1: Red", >9: Random?
I found the part that assigns colors convoluted and confusing (ie. mesh_color =... , mc = mesh_color... and color=mc), also, how to disable the background or assign a solid color to it? Any help is much appreciated, thanks!

**Comment by mkocabas** [comment]
You should modify this line:

https://github.com/mkocabas/VIBE/blob/8e57b9179250ff919b380d0a4c77534e83209a2a/demo.py#L265

Here for each `person_id` which is stored in `vibe_results.keys()` we assign a random color. You can replace `mesh_color` dictionary with something similar to this:

```
mesh_color = {
            0: [255, 0, 0], # RGB color values
            1: [0, 255, 0],
            2: [0, 0, 255],
            ...
        }
``` 

But you need to be sure that there is an entry for each `person_id` in this dictionary.
