### ISSUE TITLE
reducing the input size of the model from [1, 16, 3, 1024, 1024]

### ISSUE THREAD

**Issue by BroderickHigby** [mkocabas/VIBE#25]
I'm trying to convert the VIBE model to ONNX currently, and am running out of GPU space when I do it. The most common two answers to this are to get more GPU's and to reduce the model input size. I'm currently on a 4 GPU 128gb instance and am still running out of memory. I've tried a myriad of combinations and tried modifying the code. Is it possible to change the size of the inputs into the model from the current inputs: `x = torch.randn(1, 16, 3, 2048, 2048).type(dtype)` where the inputs are batch_size, seq_length, num_channels, size, size. 
Thank you for your help, I appreciate it. It seems that getting a bigger instance shouldn't be necessary, and that I may be missing something. 

```
... imports
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
torch_model = VIBE_Demo(
        seqlen=16,
        n_layers=2,
        hidden_size=1024,
        add_linear=True,
        use_residual=False,
    ).to(device)
model = 'data/vibe_data/vibe_model_w_3dpw.pth.tar'

map_location = lambda storage, loc: storage 
if torch.cuda.is_available():
    map_location = None
torch_model.load_state_dict(torch.load(model, map_location=torch.device('cpu')), strict=False)
torch_model.eval()
dtype = torch.cuda.FloatTensor
x = torch.randn(1, 16, 3, 2048, 2048).type(dtype)
torch_out = torch_model(x)
with torch.no_grad():
	torch.onnx.export(torch_model, 
						x,
						"vibe.onnx", 
						export_params=True,
						opset_version=10,
						do_constant_folding=True, # constant folding for optimization
						input_names = ['input'],
						output_names = ['output'],
						dynamic_axes={'input' : {0 : 'batch_size'},
										'output' : {0 : 'batch_size'}})
```

**Comment by mkocabas** [comment]
Hi @BroderickHigby,

Input should be `x = torch.randn(1, 16, 3, 224, 224).type(dtype)`. Here last two dimensions are width and height of the input images which is 224 for VIBE model. Obviously 2048 is too large.

**Comment by BroderickHigby** [comment]
oh my gosh, that makes so much sense. I figured that I was missing something when reading the paper. Also, thank you for creating VIBE, it's a fantastic architecture.

**Comment by Ironbrotherstyle** [comment]
> oh my gosh, that makes so much sense. I figured that I was missing something when reading the paper. Also, thank you for creating VIBE, it's a fantastic architecture.

Hi, did you succeed in transforming the pytorch VIBE model into ONNX model? I am curious because it contains RNN model (GRU).
