### ISSUE TITLE
Hand Motion Capability

### ISSUE THREAD

**Issue by Shreeshail-Hingane** [mkocabas/VIBE#250]
VIBE does not have the capability to track the motion of finger joints (see attached video as an example)
https://user-images.githubusercontent.com/28868617/166939826-525bbf4b-a2fb-48ee-bc53-63196969c4b4.mp4

Is there any follow-up work that has the capability to track hand fingers?

**Comment by haiderasad** [comment]
@Shreeshail-Hingane  try frank mocap https://github.com/facebookresearch/frankmocap , it has both hands plus full body and good results

**Comment by Shreeshail-Hingane** [comment]
I see, thanks. I also found other methods that has body + hands + facial expressions functionality: 
1] [SMPLify-X](https://github.com/vchoutas/smplify-x)
2] [PIXIE](https://github.com/YadiraF/PIXIE)

**Comment by haiderasad** [comment]
yes, smplify-x is being used in fankmocap as well
