### ISSUE TITLE
Question about 3D pose

### ISSUE THREAD

**Issue by lan786** [mkocabas/VIBE#3]
Hi @mkocabas  Thanks for such a valuable repository. It's amazing work. I just tested the demo for local video. There is no error and the video is saved in output is same as input video. I mean there is no 3D character in output video... 
On other side I tested this demo on Google Colab and it's working fine but in my local PC no 3D results. All the commands and commands output are same as in Google Colab. 
Can you help me to solve this problem?

**Comment by mkocabas** [comment]
Hi @lan786,

Thanks for your interest. VIBE outputs a mesh for each instance as indicated [here](https://github.com/mkocabas/VIBE/blob/master/doc/demo.md#output-format), then we render them from the camera viewpoint as a video. If you want to visualize the results in 3D, you may need to use the meshes we provide inside `vibe_output.pkl` file.

**Comment by mkocabas** [comment]
@lan786, check this [commit](https://github.com/mkocabas/VIBE/commit/1147b97e161c91fdb71e0c85a6d597c24e310229) to see how to render the outputs from an alternate view. By adding `--sideview` you may enable side view rendering.
