### ISSUE TITLE
openpose posetracker and BODY_21A

### ISSUE THREAD

**Issue by maartenjv** [mkocabas/VIBE#30]
Hello,

The posetracker runs openpose with the "--model_pose', 'BODY_21A'," setting. However, the STAF code does not seem to recognise that model (by default at least). 

-M

**Comment by mkocabas** [comment]
Did you checkout the `staf` branch locally, after cloning the repo?

**Comment by maartenjv** [comment]
Thanks, that was part of the issue.
Another issue (as posted on the staf github) is that the getModels.bat (as opposed to the getModels.sh) does not download the body_21a models.

**Comment by mkocabas** [comment]
You may download it manually. Download link should be this: http://posefs1.perception.cs.cmu.edu/OpenPose/models/body_21a_video/pose_iter_264000.caffemodel

**Comment by mingx9527** [comment]
@mkocabas 
Thank your BODY_21A model link, but the link cannot found! can you share other link???

**Comment by mkocabas** [comment]
Try to run this script: https://github.com/soulslicer/openpose/blob/staf/models/getModels.sh

**Comment by mingx9527** [comment]
> Try to run this script: https://github.com/soulslicer/openpose/blob/staf/models/getModels.sh

Thank you very much!

**Comment by anilkunchalaece** [comment]
Hi,
I checkout to the staf branch
`
* (HEAD detached at origin/staf)
  master
`
and downloaded the models using ./getModels.sh
`
├── pose
│   ├── body_21a
│   │   ├── pose_deploy.prototxt
│   │   └── pose_iter_264000.caffemodel
│   ├── body_21a_video
│   │   ├── pose_deploy.prototxt
│   │   └── pose_iter_264000.caffemodel
│   ├── body_25
│   │   ├── pose_deploy.prototxt
│   │   └── pose_iter_584000.caffemodel
│   ├── coco
`
but I'm still getting the model file not found error 
`
Caffe trained model file not found: models/pose/body_21a/pose_iter_XXXXXX.caffemodel.
`
any suggestions ?
