### ISSUE TITLE
No yolov3.cfg included in the repository

### ISSUE THREAD

**Issue by jas0n1ee** [mkocabas/VIBE#34]
After installing dependencies with `install_pip.sh` and downloading data with `prepare_data.sh`, I tried to run demo with command ` ./vibe-env/bin/python demo.py --vid_file ~/sample_video.mp4 --output_folder output/` and there is a ` No such file or directory` error regarding `${HOME}/.torch/config/yolov3.cfg`. I tried to locate the yolov3.cfg but cannot find it in this repo.

**Comment by mkocabas** [comment]
Normally, yolo config file should be automatically downloaded, check here:

https://github.com/mkocabas/yolov3-pytorch/blob/master/yolov3/yolo.py#L37-L40

If it is not downloaded, you may download it and put in under `{HOME}/.torch/config` folder.
