### ISSUE TITLE
MPoser

### ISSUE THREAD

**Issue by maartenjv** [mkocabas/VIBE#36]
Hello,

I was very interested in the sequential VAE that was trained as a motion prior (MPoser) mentioned in the paper. Is this one also included in the published code? I could not find any references/implementation of it...

Thanks

-M

**Comment by athn-nik** [comment]
We aim to publish it along with the training code soon. A rough estimate of soon is by mid April.

**Comment by maartenjv** [comment]
Thanks. Looking forward.

**Comment by maartenjv** [comment]
Hello,

I saw that a new version was released, but still cannot seem to find any reference to the MPoser. Any update on this maybe?

Thanks in advance!

**Comment by fabienbaradel** [comment]
Hi @mkocabas, same question. I cannot find any reference to MPoser? Are you using it for training?

**Comment by amituofo1996** [comment]
Hi @mkocabas , hoping you introduce some key information about MPoser, I really have a high interest in your work. Thanks!

**Comment by wang-zm18** [comment]
Hi @mkocabas, same question.
