### ISSUE TITLE
Missing bbox and frames

### ISSUE THREAD

**Issue by lan786** [mkocabas/VIBE#39]
@mkocabas  Hi, yesterday I submitted same issue #37 and you closed it after your response. 

As in this issue #37 I explained about problem and your response was that I should install STAF for tracking method (pose). 
I checked that bbox as tracking method is default so I'm not using pose as tracking method, I'm using bbox as tracking method but facing problem same to #37 
May be my this information (issue #37 ) is not enough for solution but I need your suggestions about this problem that can help me solve it.

**Comment by mkocabas** [comment]
Hi @lan786,

Could you put a breakpoint somewhere after [this line](https://github.com/mkocabas/VIBE/blob/master/demo.py#L94), and check if multi object tracker working?

**Comment by lan786** [comment]
@mkocabas  Thanks for your response. 

I just gave a try as you suggested in above comment. tracking_results [on this line](https://github.com/mkocabas/VIBE/blob/master/demo.py#L94) showing empty dict. I'm sure about it that there should be bbox and frames in tracking_results.

Furthermore at [line 71](https://github.com/mkocabas/VIBE/blob/master/demo.py#L71) in num_frames there are 301 frames, which seems that frames are there but MOT is not picking up frames and unable to define bbox. 

How I can overcome this problem?

**Comment by mkocabas** [comment]
Could you try this https://github.com/mkocabas/yolov3-pytorch? This is the package I use for YOLO.

**Comment by lan786** [comment]
Hi @mkocabas  I just gave a try to run your updated [yolov3-pytroch](https://github.com/mkocabas/yolov3-pytorch) as standalone and I got some issues I submitted new issue in that repository, that issue is also mentioned above. Kindly check that and suggest me some valuable solutions. I want to use yolo as detector in VIBE. 

Furthermore, using maskrcnn as detector with torch 1.4, I got errors. I realized that this error is due to pytorch so I changed pytorch from 1.4.0 to 1.2.0 and it works fine. The same problem arise in GoogleColab with pytorch 1.4.0 and maskrcnn, but using yolo as detector pytroch 1.4.0 also works fine in GoogleColab.

**Comment by athn-nik** [comment]
We used pytorch1.4 and it works fine. Have you both ways (cond and virtualenv) and have the same issues? Could you post your error log here and then I could give it a try to solve it. @lan786

**Comment by lan786** [comment]
@athn-nik I just tried it again on GoogleColab, now its working fine with Pytorch 1.4. By the way when training code will be released?

**Comment by Primate92587** [comment]
I keep seeing people ask about training code.....if this code doesn't include the training code then how is it possible  to run it?

**Comment by athn-nik** [comment]
The code is expected to be released by mid April. 
@Primate92587 as every ml model during inference. You have a trained model, you load the weights and network(here instantiate the network class) and then you run the model by giving it the data that it should be fed(here videos).
Then, the model gives you the output and you present it somehow(here with a video).

**Comment by Primate92587** [comment]
@athn-nik  yeah i know how ml models work...just wanted to verify that the code can't be run right now because it's basically incomplete?

**Comment by athn-nik** [comment]
Ah, ok. No, the code runs just fine. It is a demo code. A code that shows our results using an already trained model. People are just asking for training code to train a model from scratch, experiment with it and see exactly how everything works.

**Comment by Primate92587** [comment]
Got it. thanks.
