### ISSUE TITLE
Question about render the video

### ISSUE THREAD

**Issue by HumbleBone** [mkocabas/VIBE#4]
Hello @mkocabas, Thanks for your awesome works, When I was running the demo.py, something wrong happened in rendering the output video. The details are in the picture below, can you help me slove the problem.
![1](https://user-images.githubusercontent.com/36143951/70890367-d7834200-201f-11ea-84e3-21da8223747b.png)

**Comment by mkocabas** [comment]
Hi @HumbleBone,

Thanks for your interest. Problem may be related to OpenGL or Pyrender installation. Could you check [here](https://pyrender.readthedocs.io/en/latest/install/index.html#installing-a-compatible-fork-of-pyopengl) to install a compatible PyOpenGL package?

**Comment by athn-nik** [comment]
@HumbleBone you can try using install_pip.sh instead of anaconda. It will automatically set up a clean environment with the correct python version.

**Comment by HumbleBone** [comment]
@mkocabas I have tried the way you said, and I used the Virtual environment. But another problem happened?
![1](https://user-images.githubusercontent.com/36143951/70981500-357f5a80-20f0-11ea-96d0-51f404368bd1.png)

**Comment by mkocabas** [comment]
Can you try to run this [example](https://colab.research.google.com/drive/1rTLHk0qxh4dn8KNe-mCnN8HAWdd2_BEh) on your computer?

**Comment by HumbleBone** [comment]
I try to run the [example](https://colab.research.google.com/drive/1rTLHk0qxh4dn8KNe-mCnN8HAWdd2_BEh) on my computer, and the result of the operation is the same.
`RuntimeError: Validation failure (0):`

**Comment by mkocabas** [comment]
Ok, then the whole issue is with pyrender. I never encountered such an error. 

Could you open an issue on pyrender? You may find an answer there. 

I am closing the issue now, since it is not related to VIBE. Feel free to post here if you find a solution.

**Comment by HumbleBone** [comment]
Thanks for your help @mkocabas , I finally solve my problem by [this](https://github.com/mcfletch/pyopengl/issues/27). So I make pyopengl use libOpenGL.so and not libGL.so, and it works.

**Comment by xuxy09** [comment]
I am having the exact same problem. Could you please provide more details about how to solve this problem?

**Comment by athn-nik** [comment]
@xuxy09 it is an opengl problem. You can see the solution @HumbleBone provided above.

**Comment by xuxy09** [comment]
> Thanks for your help @mkocabas , I finally solve my problem by [this](https://github.com/mcfletch/pyopengl/issues/27). So I make pyopengl use libOpenGL.so and not libGL.so, and it works.

Hi @HumbleBone , can you please tell you me how you solve this problem? I am new to opengl. So the link above does not help much. Could you please provide more details? Thank you so much!
