### ISSUE TITLE
Question about papper

### ISSUE THREAD

**Issue by WinstonDeng** [mkocabas/VIBE#42]
When I read 
> During training, “VIBE” takes in-the-wild images as input and predicts SMPL body model parameters.

and 

> Then, a motion discriminator takes predicted poses along with the poses sampled from the AMASS dataset and outputs a real/fake label for each sequence.

one question that bothers me is that whether all poses from wild images are subset of AMASS dataset? If not , poses in the wild are complex and varied, so how discriminator to decide they are real by only using AMASS?

**Comment by athn-nik** [comment]
AMASS is the largest MoCap dataset, right now. It is pretty much a unified dataset of all previous MoCap datasets. So it is big enough to assume that it contains a big variety of poses and motions. We are not sure that covers the *all* of the motions that we encounter during training but it improves our results(see ablation table in the paper) and that demonstrates that it refines our pose estimations.
So the answer is we are not sure that all poses are subset of AMASS. Results show using it to discriminate between generated and true motions helps. Hence, it has a helpful enough variety of motions.

**Comment by WinstonDeng** [comment]
Thanks for your relpy！I learn a lot from your work.
