### ISSUE TITLE
W (joint regressor from vertex)? 

### ISSUE THREAD

**Issue by wangzheallen** [mkocabas/VIBE#44]
May I ask which specific model is the W in '3D Body Representation' part of the original paper to project M(\theta,\beta)  to 3d key points and what is the architecture for that?

**Comment by ikvision** [comment]
M(\theta,\beta) returns a mesh in pred_vertices in 
https://github.com/mkocabas/VIBE/blob/17b17492596621787e0ff11c8b905e91a8fae073/lib/models/spin.py#L381-L388
Given a mesh to calculate the 3d key joints it a sparse Matrix J_regressor multiplication
https://github.com/mkocabas/VIBE/blob/17b17492596621787e0ff11c8b905e91a8fae073/lib/models/spin.py#L393
As illustrated in SMPL paper:
![image](https://user-images.githubusercontent.com/11877852/76827681-a4964900-67dc-11ea-886b-b8771a8423bd.png)

**Comment by wangzheallen** [comment]
> M(\theta,\beta) returns a mesh in pred_vertices in
> https://github.com/mkocabas/VIBE/blob/17b17492596621787e0ff11c8b905e91a8fae073/lib/models/spin.py#L381-L388
> 
> 
> Given a mesh to calculate the 3d key joints it a sparse Matrix J_regressor multiplication
> https://github.com/mkocabas/VIBE/blob/17b17492596621787e0ff11c8b905e91a8fae073/lib/models/spin.py#L393
> 
> 
> As illustrated in SMPL paper:
> ![image](https://user-images.githubusercontent.com/11877852/76827681-a4964900-67dc-11ea-886b-b8771a8423bd.png)

Thanks for the reply!

**Comment by mkocabas** [comment]
Thanks @ikvision for the answer!

**Comment by ikvision** [comment]
@wangzheallen I wrote a detailed wiki on VIBE forward pass in https://github.com/ikvision/ikvision.github.io/blob/master/README.md
I hope you find it useful

**Comment by wangzheallen** [comment]
> @wangzheallen I wrote a detailed wiki on VIBE forward pass in https://ikvision.github.io/
> I hope you find it useful

Thanks! I will add your nice blogs to my https://github.com/wangzheallen/awesome-human-pose-estimation
