### ISSUE TITLE
Question about the Demo.py

### ISSUE THREAD

**Issue by Xianjin111** [mkocabas/VIBE#50]
Thank you for your perfect work. I have a problem when I ran the demo.py on Ubuntu with python 3.7 as following:

![error](https://user-images.githubusercontent.com/46471572/78009883-4341ae80-7374-11ea-83e3-e7eee7c5aa9e.PNG)

Could you please give me some suggestions? Thank you very much.

**Comment by ikvision** [comment]
opencv imread returns None if the file is missing
Can you check that the png file exists using os.path.isfile

**Comment by mkocabas** [comment]
It seems like that is an ffmpeg failure. Could you try to run a simple ffmpeg example to see if that works?

**Comment by Xianjin111** [comment]
> It seems like that is an ffmpeg failure. Could you try to run a simple ffmpeg example to see if that works?

Thank you. It's solved. I re-installed the ffmpeg in Anaconda from https://anaconda.org/menpo/ffmpeg/files.
