### ISSUE TITLE
[BUG] Missing load_mean_dict function for in case use_6d is False

### ISSUE THREAD

**Issue by mtngld** [mkocabas/VIBE#51]
First, thank you for your great research and making the code available.

https://github.com/mkocabas/VIBE/blob/731c27382978e242fc1492c4bf53ddd72fd345de/lib/models/spin.py#L335 the function `load_mean_dict` is imported from `lib.models.hmr`

But there doesn't seem to be a `hmr` module in the code, I assume it is based on the [original](https://github.com/akanazawa/hmr/blob/537f1b2c91beb71cb61a388bf8f6504516b875a8/src/trainer.py#L179) `hmr` code?

**Comment by mkocabas** [comment]
Hi @mtngld,

Thanks for your interest. That part is unused, I forgot to delete that part. We only use 6D representation as the output. We used an HMR model reimplemented in pytorch to perform ablation experiments, but it is not included in this repo.
