### ISSUE TITLE
[FEATURE] For half-body estimation

### ISSUE THREAD

**Issue by AlexHu123** [mkocabas/VIBE#53]
Thanks for your great work!
I run some demo but find it difficult to generalize on the video when only upper body is captured, would it be possible for you to give me some suggestions on how to modify your code to fit for half-body capture?

**Comment by ikvision** [comment]
I think tuning the crop as suggest in https://github.com/mkocabas/VIBE/issues/24#issuecomment-582045077 to have enough zero padding as a full body may help.
But I think that ultimately better dealing with half body capture requires re-training with this type of data.

**Comment by ikvision** [comment]
For example in SPIN, images without all major body joints are not incorporated during the training 
https://github.com/nkolot/SPIN/blob/277892a91e74af004c74457cd294bd102972f9b0/datasets/preprocess/coco.py#L34-L36

**Comment by athn-nik** [comment]
@AlexHu123 I think it is mostly engineering. A quick brute-force solution could be to post-process the data and discard the part of the mesh(set of vertices) that its joints are invisible in the image/frame. SMPL returns you all the things you want for it. During training a similar workaround is possible I think. 
If you implement any of these I am happy to help merging in into the current model :)
