### ISSUE TITLE
Eliminating hip lock to the center.

### ISSUE THREAD

**Issue by abdullahchand** [mkocabas/VIBE#54]
Hi mkocabas, Thanks for the great work!. 
I used the joints3d extracted from the result to animate a rig. The animation turns out great but I am having an issue where the animated character is "locked in place (hip locked)". I have been trying to remove the hip lock. To do this I added the projection pose to the joints3d x and y but that results in the character floating. Need Help on how I can remove the hip lock, and have proper motion.

Thanks in Advance.

**Comment by hellozjj** [comment]
> Hi mkocabas, Thanks for the great work!.
> I used the joints3d extracted from the result to animate a rig. The animation turns out great but I am having an issue where the animated character is "locked in place (hip locked)". I have been trying to remove the hip lock. To do this I added the projection pose to the joints3d x and y but that results in the character floating. Need Help on how I can remove the hip lock, and have proper motion.
> 
> Thanks in Advance.

@abdullahchand  Do you solve this?

**Comment by hellozjj** [comment]
@abdullahchand  Does it mean in the output file, the position for the hip is not moving?

**Comment by mkocabas** [comment]
Hi @abdullahchand,

Thanks for your interest. Currently, the output body joints are in camera coordinate system and it is not easy to extend it to global coordinate system. One needs to have camera calibration and the absolute depth of the subject to the camera.

**Comment by abdullahchand** [comment]
@mkocabas Thanks for your reply.

If I am able to get the camera calibration and get the actual prespective projection. How will I go about achieveing my solution to this?. You use SMPLfyX for refinement and SMPLfyX already predicts the position of the root. Would it be possible to achieve what I want to achieve by outputing the global_orientation from the smplfy model? How would it work?

Also the length of pose in smplfyX is 63 that is 21 joints but you output pose as 72  that is 24 joints? . Can you tell me about the ordering of these joints compared to the smplfyX? 

Thanks,

**Comment by ikvision** [comment]
@abdullahchand I think DeepCap shows HMR model "hip lock" during the first few seconds of this video:
[https://youtu.be/C4eDrvJ9aBs?t=4](url) as the person moves forward its 3d z position doesn't change. Maybe using depth information during training, as DeepCap, can help VIBE estimate absolute depth.

**Comment by ikvision** [comment]
Concerning the 24 joints, corresponding to the predicted rotation matrix they are marked in https://github.com/ikvision/ikvision.github.io/raw/master/assets/images/kinematic_tree.png
I think the issue dealing with matching it to the SMPLfyX  21 joints is: https://github.com/vchoutas/smplify-x/issues/58#issuecomment-582052164
