### ISSUE TITLE
Some thinking about online inference

### ISSUE THREAD

**Issue by lszh2015** [mkocabas/VIBE#56]
Hello Mkocabas, thanks for your wonderful job! From messages in #40 , It seems that the gap to online inference is the online tracking method. Is it possible to use some accurate online pose tracking method such as OpenPose, AlphaPose, etc? 

however, as far as I acknowledge, is it possible that the temporal effect will disappear when online applied?(I suppose the batchsize will be set to 1 when online.) Could you please describe the detail of realizing VIBE online? Or could you please share the code of online VIBE? (only VIBE, maybe not including tracker).

Waiting for your apply.  Thank you!

**Comment by athn-nik** [comment]
There are a couple of things that we should consider for the online version of VIBE. There is a lot of software engineering work involved to make this work online realtime.If we decide to go for a demo we will do so.
To conclude, this repo will not be updated with any online any time soon. This week the training code will be released.

**Comment by athn-nik** [comment]
@lszh2015 Let me know if you have any other questions or need further help. Otherwise, we will close this issue for now.
