### ISSUE TITLE
Training Code for Master-Thesis

### ISSUE THREAD

**Issue by marcvoegele-fhnw** [mkocabas/VIBE#59]
Hello,
for my Master-Thesis i should test 3D-Pose-Estimation approaches for a specific case.
Could you send me the Training-Code (maybe a prototype) for my Project?

Kind regards
Marc

**Comment by Primate92587** [comment]
We're all waiting . I check every day. It's supposed to be released 'soon' but hard to say when (this month? in a few months?)

https://github.com/mkocabas/VIBE/issues/6

**Comment by athn-nik** [comment]
Soon is this week @Primate92587 @marcvoegele-fhnw . We are working to make it easier for everyone to use.

**Comment by donghaoye** [comment]
Same with the all above

**Comment by Frank-Dz** [comment]
> Soon is this week @Primate92587 @marcvoegele-fhnw . We are working to make it easier for everyone to use.

Hi~ Is the trainning code OK?

Thanks!

Best,
Frank

**Comment by mkocabas** [comment]
It is released, see https://github.com/mkocabas/VIBE/commit/2ba005c0f2d5e42c15bc8057ab7ad5584192d717
