### ISSUE TITLE
Train code

### ISSUE THREAD

**Issue by kallivad** [mkocabas/VIBE#6]
Hi @mkocabas, great thanks for your awersome work!!
Have you any plans of sharing train code for VIBE and it's HMR concerned components?

**Comment by mkocabas** [comment]
Yes, we plan to release it but the exact date is unknown at the moment. I will update here.

**Comment by MengXinChengXuYuan** [comment]
Hi any plan to release the code? :p

**Comment by mkocabas** [comment]
Hi @MengXinChengXuYuan,

Yes, we are working on to make it before March 23.

**Comment by Vegetebird** [comment]
Hi, the trainning code is released?

**Comment by mkocabas** [comment]
Hi @Vegetebird, unfortunately not. We are working on it and release it soon. Thanks for your understanding.

**Comment by Frank-Dz** [comment]
Hi, the trainning code is released?

**Comment by athn-nik** [comment]
The training code will be uploaded this week. Thanks for your patience!

**Comment by mkocabas** [comment]
Hi all,

We have released the training code, see It is released, see https://github.com/mkocabas/VIBE/commit/2ba005c0f2d5e42c15bc8057ab7ad5584192d717.
