### ISSUE TITLE
Details about data processing

### ISSUE THREAD

**Issue by Xianjin111** [mkocabas/VIBE#60]
Thanks for your perfect work.  Could you please provide more details about how to pre-process the 3DPW datasets for training. Thank you very much.

**Comment by ikvision** [comment]
The pre-processing code for VIBE is not yet available, but it is detailed in SPIN
https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md
The code is in https://github.com/nkolot/SPIN/blob/277892a91e74af004c74457cd294bd102972f9b0/datasets/preprocess/pw3d.py

**Comment by athn-nik** [comment]
We will upload the training code this week. But @ikvision is more or less correct!Thanks @ikvision

**Comment by Xianjin111** [comment]
> The pre-processing code for VIBE is not yet available, but it is detailed in SPIN
> https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md
> The code is in https://github.com/nkolot/SPIN/blob/277892a91e74af004c74457cd294bd102972f9b0/datasets/preprocess/pw3d.py

Thank you very much for your suggestion.

**Comment by Xianjin111** [comment]
> We will upload the training code this week. But @ikvision is more or less correct!Thanks @ikvision

The news sounds exciting. Thank you so much for your support.
