### ISSUE TITLE
Is the joints3d in the output the global positions of joints or int the camera space? 

### ISSUE THREAD

**Issue by hellozjj** [mkocabas/VIBE#63]
Is the joints3d in the output the global positions of joints or int the camera space?

**Comment by hellozjj** [comment]
In other word, I want to know if the root(hip) joint is fixed. I want to get the global position of the root joint.
Thanks for any advices.

**Comment by mkocabas** [comment]
Hip and the other joints are not in global coordinate system.

**Comment by hellozjj** [comment]
> Hip and the other joints are not in global coordinate system.

@mkocabas  So is it in camera coordinate system? If not, what's coordinate system it in? And is the root position fixed?

**Comment by HenriMir** [comment]
hello @hellozjj , have you figured it ? I'm asking the same questions

**Comment by jet-zheng** [comment]
@hellozjj  have you got it done? I want to do the same thing.
