### ISSUE TITLE
output pickle file (vibe_output.pkl) seems to be invalid 

### ISSUE THREAD

**Issue by jaygit123** [mkocabas/VIBE#65]
Hi @mkocabas, 

Thanks for this awesome implementation of VIBE. Works very good on video input. 

But for some reason the output pickle file (vibe_output.pkl) seems to be invalid and is unusable. 
'KeyError: 1' is thrown when I try to get keys in it.
NOTE: I am using --tracking_method as 'pose' and use STAF extension of OpenPose (BODY_25).

**Environment details**
1. Google Colab notebook with Ubuntu 18.04.3 LTS
2. Python version 3.6.9
3. Pytorch - version 1.4.0 and cuDNN version : 7603
4. Error noticed while trying to read the output pickle file (vibe_output.pkl) is given below:

**Error**

> Track ids: dict_keys([-1])

> VIBE output file content:
> KeyError                                  Traceback (most recent call last)
> <ipython-input-38-3bd20e84f0e1> in <module>()
>       4 
>       5 print('VIBE output file content:', end='\n\n')
> ----> 6 for k,v in output[1].items():
>       7   if k != 'joints2d':
>       8     print(k, v.shape)
> 
> KeyError: 1

You can check the generated pkl file and mp4 files in this location:
[VIBE-output-pkl-error.zip](https://drive.google.com/file/d/1-15ghwv4lcEqGl1LjuzgxlmHj820wzTh/view?usp=sharing)

I noticed someone else also had mentioned that the generated pickle file is unusable. 
**Could you please help resolving this issues please?** 

**NOTE:** 
This is how I am trying to read the pkl file:
```
# Inspect the output file content
import joblib
output = joblib.load('/content/VIBE/output/output/vibe_output.pkl')
print('Track ids:', output.keys(), end='\n\n')

print('VIBE output file content:', end='\n\n')
for k,v in output[1].items():
  if k != 'joints2d': 
    print(k, v.shape)
```

Thanks & Regards,
Jay

**Comment by mkocabas** [comment]
Hi @jaygit123,

Thanks for your interest. I just tested the demo on google drive and it worked as expected. Could you try once again?

**Comment by jaygit123** [comment]
Hi @mkocabas ,
Thanks for awesome quick response. I have checked once again and still getting the same error with respect to pkl file. Not sure what's wrong.

BTW, I have just made these minor changes to 'VIBE/lib/utils/pose_tracker.py' file. 
1. added params --face & --hand to the params list of openpose.bin command
2. changed value of param --model_pose from BODY_21A to BODY_25
3. With the above changes, the resultant call of openpose is like the below:

> openpose.bin --video /content/output.mp4 --write_json /tmp/output.mp4_posetrack --display 0 --model_pose BODY_25 --face --hand --hand_detector 0 --render_pose 0

Could the above changes cause generated pkl file to be unusable? 

One more question (not related to pkl file)...please answer.
Even though openpose gives 2D keypoints of face and hands (along with body keypoints), I see they are not used in the final 3D model (facial expression and fingers do not change as per the pose in video). Is there a way to enable facial expression and fingers movements to sync with that of video input? Please share some pointers. 

Regards,
Jay

**Comment by ikvision** [comment]
I think the difference you mention in open pose is not the only change required, it requires changing the body model too.
Mesh's facial expression and fingers are related to the usage of SMPLX body model, as it includes face and fingers 3d keypoints:
![image](https://user-images.githubusercontent.com/11877852/80248596-17d57b00-8625-11ea-99c0-987d71d3d93e.png)
Currently VIBE uses SMPL:
https://github.com/mkocabas/VIBE/blob/2ba005c0f2d5e42c15bc8057ab7ad5584192d717/lib/models/smpl.py#L7
SMPL key points are shown in: [SMPL_mesh](https://ikvision.github.io/assets/images/Joint_regression_frame.png)

One should integrate SMPLX model for training and prediction flow
`from smplx.body_models import  SMPLX`

**Comment by mkocabas** [comment]
> added params --face & --hand to the params list of openpose.bin command

Even though you add face and hand, you would not be able to use them since VIBE does not support SMPL-X body model. Also, staf pose tracker does not support the tracking of face and hand keypoints.

> changed value of param --model_pose from BODY_21A to BODY_25

You should not do that, because pose tracking is only supported through BODY_21A model. BODY_25 model will not give you tracking info.

I suppose the above modifications are the main cause for your problem.

> Is there a way to enable facial expression and fingers movements to sync with that of video input?

VIBE currently does not support SMPL-X models which includes face and hands as @ikvision mentioned. And it is not trivial to implement for the time being.

**Comment by jaygit123** [comment]
Hello @mkocabas, 
Thanks for the detailed response. Got it. 

Hello @ikvision, 
Thanks for your inputs. I shall explore implementing SMPL-X. If you know any repo that already has implemented this (SMPL-X with openpose body, face & hands keypoints) kindly point me to it.
