### ISSUE TITLE
Motion Discriminator's weights.

### ISSUE THREAD

**Issue by OOF-dura** [mkocabas/VIBE#67]
Hi! We want to treat the discriminator (trained based on AMASS) as a separate module. 
Is it possible to obtain the model weights of the discriminator alone? 
Or do we have to re-train the discriminator?

Thanks!

**Comment by OOF-dura** [comment]
@mkocabas @athn-nik Or if it is possible to share the weights of discriminator?

Thanks!

**Comment by mkocabas** [comment]
Hi @OOF-dura,

Thanks for your interest. Sure, I uploaded it [here](https://www.dropbox.com/s/amj2p8bmf6g56k6/vibe_model_wo_3dpw.pth.tar?dl=0). Get the `disc_motion_state_dict` key after loading it via `torch.load(filename)`.

**Comment by OOF-dura** [comment]
> Hi @OOF-dura,
> 
> Thanks for your interest. Sure, I uploaded it [here](https://www.dropbox.com/s/amj2p8bmf6g56k6/vibe_model_wo_3dpw.pth.tar?dl=0). Get the `disc_motion_state_dict` key after loading it via `torch.load(filename)`.

@mkocabas hi~
Tried but failed:
```
from lib.utils.demo_utils import download_ckpt
import os
os.environ['PYOPENGL_PLATFORM'] = 'egl'
import torch
from lib.core.config import *
from lib.utils.utils import prepare_output_dir
from lib.models import  MotionDiscriminator
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

cfg_file ='configs/config.yaml'
cfg = update_cfg(cfg_file)

cfg = prepare_output_dir(cfg, cfg_file)
print(cfg)

motion_discriminator = MotionDiscriminator(
    rnn_size=cfg.TRAIN.MOT_DISCR.HIDDEN_SIZE,
    input_size=69,
    num_layers=cfg.TRAIN.MOT_DISCR.NUM_LAYERS,
    output_size=1,
    feature_pool=cfg.TRAIN.MOT_DISCR.FEATURE_POOL,
    attention_size=None if cfg.TRAIN.MOT_DISCR.FEATURE_POOL != 'attention' else cfg.TRAIN.MOT_DISCR.ATT.SIZE,
    attention_layers=None if cfg.TRAIN.MOT_DISCR.FEATURE_POOL != 'attention' else cfg.TRAIN.MOT_DISCR.ATT.LAYERS,
    attention_dropout=None if cfg.TRAIN.MOT_DISCR.FEATURE_POOL != 'attention' else cfg.TRAIN.MOT_DISCR.ATT.DROPOUT
).to(device)

pretrained_file = download_ckpt(use_3dpw=False)
ckpt = torch.load(pretrained_file)
get_state_dict = ckpt['gen_state_dict']
for keys in get_state_dict.keys():
    print(keys)
motion_discriminator.load_state_dict(ckpt['disc_motion_state_dict'])
```
The error is :
```
Traceback (most recent call last):
  File "/home/frank/PycharmProjects/VIBE_train/Test_discriminator.py", line 32, in <module>
    motion_discriminator.load_state_dict(ckpt['disc_motion_state_dict'])
  File "/home/frank/PycharmProjects/VIBE/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MotionDiscriminator:
	Missing key(s) in state_dict: "attention.attention.0.weight", "attention.attention.0.bias", "attention.attention.3.weight", "attention.attention.3.bias", "attention.attention.6.weight", "attention.attention.6.bias". 
	size mismatch for fc.weight: copying a param with shape torch.Size([1, 2048]) from checkpoint, the shape in current model is torch.Size([1, 1024]).
```

Thanks!

**Comment by mkocabas** [comment]
You need to change [this line](https://github.com/mkocabas/VIBE/blob/master/configs/config.yaml#L47) to 2048.

**Comment by mkocabas** [comment]
Oh no, you need to set [this line](https://github.com/mkocabas/VIBE/blob/master/configs/config.yaml#L44) to 'concat'

**Comment by OOF-dura** [comment]
> You need to change [this line](https://github.com/mkocabas/VIBE/blob/master/configs/config.yaml#L47) to 2048.

Thanks! Changed, but still got:
![image](https://user-images.githubusercontent.com/22954901/80283659-e3101380-874b-11ea-91c5-df375796abbd.png)

![image](https://user-images.githubusercontent.com/22954901/80283637-b22fde80-874b-11ea-9c6e-dbc097c5048a.png)
```
Traceback (most recent call last):
  File "/home/frank/PycharmProjects/VIBE_train/Test_discriminator.py", line 32, in <module>
    motion_discriminator.load_state_dict(ckpt['disc_motion_state_dict'])
  File "/home/frank/PycharmProjects/VIBE/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MotionDiscriminator:
	Missing key(s) in state_dict: "attention.attention.0.weight", "attention.attention.0.bias", "attention.attention.3.weight", "attention.attention.3.bias", "attention.attention.6.weight", "attention.attention.6.bias". 
	size mismatch for fc.weight: copying a param with shape torch.Size([1, 2048]) from checkpoint, the shape in current model is torch.Size([1, 1024]).

```
Thanks!

**Comment by OOF-dura** [comment]
@mkocabas great. [https://github.com/mkocabas/VIBE/issues/67#issuecomment-619395558](https://github.com/mkocabas/VIBE/issues/67#issuecomment-619395558) works for me!
Thanks again.
Btw, have you ever tested this model for judging one single pose rather a pose sequence?

Anyway, thank you.

**Comment by mkocabas** [comment]
There is already a method doing it called [Human Mesh Recovery](https://github.com/akanazawa/hmr). They use a single pose discriminator to distinguish plausible ones.

**Comment by Frank-Dz** [comment]
ok！thanks！





On 04/25/2020 23:38, Muhammed Kocabas wrote:

There is already a method doing it called Human Mesh Recovery. They use a single pose discriminator to distinguish plausible ones.
