### ISSUE TITLE
[BUG] name 'Insta' is not defined

### ISSUE THREAD

**Issue by Gorosia** [mkocabas/VIBE#68]
Thanks for this wonderful implementation of VIBE!

I followed your 'README.md' file.

'demo.py', 'eval.py' worked.

But when I try training VIBE.

I got error 'NameError: name 'Insta' is not defined'

I already download 'insta_train_db.h5'.

How can I solve this problem?

Thanks!

**Comment by mkocabas** [comment]
Hi @Gorosia,

My latest commit https://github.com/mkocabas/VIBE/commit/8e7d65bd898394f543d212f9cc7b12381bf46803 should solve this. Could you pull and try again?

**Comment by Gorosia** [comment]
It seems work! Thanks again!

**Comment by wang-zm18** [comment]
> Thanks for this wonderful implementation of VIBE!
> 
> I followed your 'README.md' file.
> 
> 'demo.py', 'eval.py' worked.
> 
> But when I try training VIBE.
> 
> I got error 'NameError: name 'Insta' is not defined'
> 
> I already download 'insta_train_db.h5'.
> 
> How can I solve this problem?
> 
> Thanks!

Hello, could you please tell me how to download "insta_train_db.h5" file? Thank you in advance!
