### ISSUE TITLE
How to get 3D joint locations from SMPL Parameters?

### ISSUE THREAD

**Issue by cbsudux** [mkocabas/VIBE#71]
Hi,

I am running demo.py on the sample video, and I see that the SMPL 3D joints are saved (#Frames, 49,3). 

I want to visualize the 3D joints and the 3D Pose only (not the mesh). How do I do this?

**Comment by mkocabas** [comment]
Hi @cbsudux,

You may check this function: https://github.com/mkocabas/EpipolarPose/blob/master/lib/utils/vis.py#L34 and a sample usage of it: https://github.com/mkocabas/EpipolarPose/blob/master/demo.ipynb

**Comment by cbsudux** [comment]
Thanks.

What are the connections for the SMPL model? 

I see that's it has 25+24 joints (49) in total. However https://github.com/mkocabas/EpipolarPose/blob/master/lib/utils/vis.py#L34 only has for MPII and H3.6M.

**Comment by mkocabas** [comment]
Here is the definitions of 49 joints: https://github.com/mkocabas/VIBE/blob/master/lib/data_utils/kp_utils.py#L212. You can use this as connection: https://github.com/mkocabas/VIBE/blob/master/lib/data_utils/kp_utils.py#L128

**Comment by cbsudux** [comment]
Thanks!

I have one more question. It looks like the (49,3) joints3D output from SMPL are joint rotations. How do I convert them into 3D joint positions (x,y,z) that can be plotted?

**Comment by mkocabas** [comment]
The 3D joint coordinates are saved as "joints3d" in the final output file. Rotations are "pose".

**Comment by cbsudux** [comment]
Oh okay thanks! Are "joints3d" predicted by the model directly or are they regressed from "pose"?

**Comment by ikvision** [comment]
The "joints3d" are not predicted directly, the HMR model regress body_pose and body_shape. 
The SMPL model generate from HMR outputs the "joints3d" using few more steps describe in VIBE/SPIN papers and in https://ikvision.github.io/

**Comment by hoolizou** [comment]
Hi~what is the meaning of 'OP' prefix  and what the different between "OP LKnee" and “lknee”？
 [https://github.com/mkocabas/VIBE/blob/master/lib/data_utils/kp_utils.py#L212](url)

**Comment by SunYangtian** [comment]
> Hi~what is the meaning of 'OP' prefix and what the different between "OP LKnee" and “lknee”？https://github.com/mkocabas/VIBE/blob/master/lib/data_utils/kp_utils.py#L128

It seems that keypoints with 'OP' prefix corresponds with the OpenPose keypoints (BODY_25) definition.  However, the difference  between "OP LKnee" and “lknee” also confuses me.
