### ISSUE TITLE
[BUG] Each obj file's faces are different in demo.py

### ISSUE THREAD

**Issue by ikvision** [mkocabas/VIBE#72]
Thanks for your great research and very well maintained code.

1. Operating system and the version - Ubuntu 18
2. Python version, 3.7
3. Any txt diff between two obj file reveals the difference

When running the demo code with --save_obj the faces are different for every frame. 
One should expect that v (vertices) section should be different as the body moves. But the f (faces) section should remain constant as the smpl faces are given by `from lib.models.smpl import get_smpl_faces`.  
Trimesh seems to calculate the faces for each frame and therefor each obj file has a different f (faces) section in https://github.com/mkocabas/VIBE/blob/2ba005c0f2d5e42c15bc8057ab7ad5584192d717/lib/utils/renderer.py#L86

Trimesh is a general tool trying to optimize the mesh for and is not aware of SMPL consistency needs. I didn't find a way to avoid those optimizing faces in Trimesh. But a simple solution in VIBE code would be to overwrite the f section by get_smpl_faces values for each frame.

I think this consistency would simplify the conversion to an animation file (as fbx file)

**Comment by mkocabas** [comment]
Hi @ikvision,

It is something related to trimesh package, commit https://github.com/mkocabas/VIBE/commit/e7b1cff7a7b991ab703f2cfd60304e1b470fbacf should solve this.

**Comment by ikvision** [comment]
Wow, thank you for the quick fix

**Comment by Primate92587** [comment]
how are you doing the conversion to an fbx file?

**Comment by Primate92587** [comment]
how are you doing the conversion to an fbx file?

**Comment by ikvision** [comment]
@Primate92587 conversion the fbx is a feature request https://github.com/mkocabas/VIBE/issues/1 not yet implemented
