### ISSUE TITLE
 No module named 'lib'[BUG]

### ISSUE THREAD

**Issue by sorrowyn** [mkocabas/VIBE#75]
when i try run lib\data_utils\amass_utils.py
error:
ModuleNotFoundError: No module named 'lib'

But you mentioned that throughout the documentation we refer to VIBE root folder as $ROOT.

**Comment by sorrowyn** [comment]
export PYTHONPATH=/***:$PYTHONPATH

**Comment by athn-nik** [comment]
@sorrowyn thanks for noting it. We will update README
