### ISSUE TITLE
[BUG]KeyError: 'poses is not a file in the archive'

### ISSUE THREAD

**Issue by Liuxinyue521** [mkocabas/VIBE#76]
Operating system: ubuntu 18.04
Python version: 3.7.5
Pytorch version: torch==1.4.0, torchvision==0.5.0, torchgeometry==0.1.2
When processing amass dataser, the error happened: 
Reading ACCAD sequence...
100%|███████████████████████████████████████████| 20/20 [00:00<00:00, 38.96it/s]
ACCAD number of videos 192553
Reading BioMotionLab_NTroje sequence...
100%|█████████████████████████████████████████| 111/111 [00:08<00:00, 13.55it/s]
BioMotionLab_NTroje number of videos 3763254
Reading CMU sequence...
  2%|▊                                          | 2/102 [00:00<00:14,  6.89it/s]
Traceback (most recent call last):
  File "lib/data_utils/amass_utils.py", line 139, in <module>
    db = read_data(args.dir, sequences=all_sequences)
  File "lib/data_utils/amass_utils.py", line 69, in read_data
    thetas, vid_names = read_single_sequence(seq_folder, seq_name)
  File "lib/data_utils/amass_utils.py", line 93, in read_single_sequence
    pose = data['poses'][:, joints_to_use]
  File "/media/data/student_directories/shuliu/VIBE/vibe-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'poses is not a file in the archive'

I donnot know why this is happening. And in my amass folder, only the bodydata part of the amass dataset is included.
Hope someone can help me about this, thanks in advance

**Comment by lan786** [comment]
@Liuxinyue521  I'm also facing same issue. Did you solve it?

**Comment by Liuxinyue521** [comment]
> @Liuxinyue521 I'm also facing same issue. Did you solve it?

No I didnot find the solution. I skip CMU dataset and it worked, so I think something is wrong with the CMU dataset... If you find other better solution, please tell me as well, thanks.

**Comment by mkocabas** [comment]
Hi,

Some sequences in CMU is formatted differently than the rest. Please pull my latest commit to avoid this issue. Thanks.
