### ISSUE TITLE
[BUG]ValueError: data/vibe_db/mpii3d_train_db.pt do not exists

### ISSUE THREAD

**Issue by Liuxinyue521** [mkocabas/VIBE#77]
Operating system: ubuntu 18.04
Python version: 3.7.5
Pytorch version: torch==1.4.0, torchvision==0.5.0, torchgeometry==0.1.2
When processing mhi_inf_3dhp dataset, it ended with 'Killed' notice:
![image](https://user-images.githubusercontent.com/57157406/81712280-01457580-94a7-11ea-8833-cf19cd748f2c.png)
and when start training, this error happens. And indeed, there is no mpii3d_train_db.pt in the vibe-db folder.
Lists of files in vibe_db are: 3dpw_test_db.pt   amass_db.pt        pennaction_train_db.pt
3dpw_train_db.pt  insta_train_db.h5  posetrack_train_db.pt
3dpw_val_db.pt    mpii3d_val_db.pt
If someone knows how to solve this, please tell me and I would really appreciate it. Thanks in advance.

**Comment by mkocabas** [comment]
@Liuxinyue521 what is your RAM size? The mpii3d preprocessing script might be killed due to insufficient RAM.

**Comment by Liuxinyue521** [comment]
> @Liuxinyue521 what is your RAM size? The mpii3d preprocessing script might be killed due to insufficient RAM.

Thanks for your reply! I will free some space and try it again.

**Comment by Liuxinyue521** [comment]
> @Liuxinyue521 what is your RAM size? The mpii3d preprocessing script might be killed due to insufficient RAM.
By the way, how much RAM needed for this processing?

**Comment by mkocabas** [comment]
I don't know exactly but I tested the code on machines with 32 and 64GB RAM.

**Comment by lan786** [comment]
@mkocabas  I've completed pre-processing of all mentioned datasets. When I start training I got this error `mpii3d_train_db.pt do not exists`  I checked the vibe_db folder and there is no exactly `mpii3d_train_db.pt` file. There is `mpii3d_spin_db.pt` file. So if we rename the `mpii3d_spin_db.pt` to `mpii3d_train_db.pt` then is it ok?

**Comment by mkocabas** [comment]
@lan786 yes, that was a typo. Thanks for noting this!

**Comment by Liuxinyue521** [comment]
> I don't know exactly but I tested the code on machines with 32 and 64GB RAM.

Hi, I still get this error. Could you tell me how to do this processing in a not-that-large-RAM machine? Like reducing the batch size? Or alternatively, could you send me the processed datasets directly to me? I would appreciate it if you can help me about this.

**Comment by lixincheng4026** [comment]
> @mkocabas I've completed pre-processing of all mentioned datasets. When I start training I got this error `mpii3d_train_db.pt do not exists` I checked the vibe_db folder and there is no exactly `mpii3d_train_db.pt` file. There is `mpii3d_spin_db.pt` file. So if we rename the `mpii3d_spin_db.pt` to `mpii3d_train_db.pt` then is it ok?

I download this dataset via https://upenn.box.com/PennAction, but found it is invlid. How can you get PennAction?

**Comment by Vegetebird** [comment]
> > @mkocabas I've completed pre-processing of all mentioned datasets. When I start training I got this error `mpii3d_train_db.pt do not exists` I checked the vibe_db folder and there is no exactly `mpii3d_train_db.pt` file. There is `mpii3d_spin_db.pt` file. So if we rename the `mpii3d_spin_db.pt` to `mpii3d_train_db.pt` then is it ok?
> 
> I download this dataset via https://upenn.box.com/PennAction, but found it is invlid. How can you get PennAction?

I can't download this dataset via https://upenn.box.com/PennAction, could you help me?

**Comment by dongfang-a** [comment]
After run prepare_training_data, I cannot find mpii3d_train_db.pt, pennaction_train_db.pt, 3dpw_train_db.pt 
The list I have is: 3dpw_test_db.pt amass_db.pt, insta_train_db.h5, posetrack_train_db.pt, 3dpw_val_db.pt, mpii3d_val_db.pt

And in the code threedpw_utils.py I didn't find anything about "3dpw_train_db.pt". 
In mpii3d_utils.py, I didn't find where it convert avi files to images but it need image files in read_data_train function.

Can anyone help?

**Comment by GQZxn** [comment]
How do you solve this problem? Do you have a file download address？

data/vibe_db/mpii3d_train_db.pt do not exists

**Comment by JacobLiu-S** [comment]
> How do you solve this problem? Do you have a file download address？
> 
> data/vibe_db/mpii3d_train_db.pt do not exists

You can just download the original dataset and follow the preprocessing readme. It should work.

**Comment by GQZxn** [comment]
> 
MPII3D Dataset overlap ratio:  0
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    main(cfg)
  File "train.py", line 60, in main
    data_loaders = get_data_loaders(cfg)
  File "/home/jsj_21_07/VIBE/lib/dataset/loaders.py", line 53, in get_data_loaders
    train_3d_db = get_3d_datasets(train_3d_dataset_names)
  File "/home/jsj_21_07/VIBE/lib/dataset/loaders.py", line 33, in get_3d_datasets
    db = eval(dataset_name)(set='train', seqlen=cfg.DATASET.SEQLEN, debug=cfg.DEBUG)
  File "/home/jsj_21_07/VIBE/lib/dataset/mpii3d.py", line 36, in __init__
    debug=debug,
  File "/home/jsj_21_07/VIBE/lib/dataset/dataset_3d.py", line 41, in __init__
    self.db = self.load_db()
  File "/home/jsj_21_07/VIBE/lib/dataset/dataset_3d.py", line 56, in load_db
    raise ValueError(f'{db_file} do not exists')
ValueError: data/vibe_db/mpii3d_train_db.pt do not exists

Still remind me that this file is missing！！！

**Comment by JacobLiu-S** [comment]
> > 
> 
> MPII3D Dataset overlap ratio: 0 Traceback (most recent call last): File "train.py", line 162, in main(cfg) File "train.py", line 60, in main data_loaders = get_data_loaders(cfg) File "/home/jsj_21_07/VIBE/lib/dataset/loaders.py", line 53, in get_data_loaders train_3d_db = get_3d_datasets(train_3d_dataset_names) File "/home/jsj_21_07/VIBE/lib/dataset/loaders.py", line 33, in get_3d_datasets db = eval(dataset_name)(set='train', seqlen=cfg.DATASET.SEQLEN, debug=cfg.DEBUG) File "/home/jsj_21_07/VIBE/lib/dataset/mpii3d.py", line 36, in **init** debug=debug, File "/home/jsj_21_07/VIBE/lib/dataset/dataset_3d.py", line 41, in **init** self.db = self.load_db() File "/home/jsj_21_07/VIBE/lib/dataset/dataset_3d.py", line 56, in load_db raise ValueError(f'{db_file} do not exists') ValueError: data/vibe_db/mpii3d_train_db.pt do not exists
> 
> Still remind me that this file is missing！！！

Do you successfully run the [preprocess script](https://github.com/mkocabas/VIBE/blob/master/scripts/prepare_training_data.sh)?
