### ISSUE TITLE
Lack of AMASS ”BioMotionLab_NTroje“ dataset

### ISSUE THREAD

**Issue by flyyyyer** [mkocabas/VIBE#78]
In the "https://amass.is.tue.mpg.de/dataset", there are only ”BMLrub“ and  ”BMLmovi” dataset, how can I download ”BioMotionLab_NTroje“ dataset?

**Comment by Liuxinyue521** [comment]
> In the "https://amass.is.tue.mpg.de/dataset", there are only ”BMLrub“ and ”BMLmovi” dataset, how can I download ”BioMotionLab_NTroje“ dataset?

When you download the BMLrub, you'll get .tar.bz2 file and after untar the file you'll get BioMotionLab_NTroje.

**Comment by athn-nik** [comment]
Thanks, @Liuxinyue521 . @flyyyyer should I mark this as closed?

**Comment by flyyyyer** [comment]
Thanks, @Liuxinyue521. I get another problem, could you help me?
![image](https://user-images.githubusercontent.com/56632276/82022952-10534000-96c0-11ea-99c6-aa19de6f88e7.png)

**Comment by mkocabas** [comment]
@flyyyyer, please pull the latest commits solving this issue. Check here https://github.com/mkocabas/VIBE/issues/76.

**Comment by 19552651958** [comment]
How should I solve this on Windows 10 and Python 3.7? I encountered this error when trying to run the PoseFix open source project.
