### ISSUE TITLE
View meshes from different angles?

### ISSUE THREAD

**Issue by AlleUndKalle** [mkocabas/VIBE#8]
How can I view the predicted meshes from different angles?

**Comment by mkocabas** [comment]
You may pass `--sideview` flag to demo script. By default it rotates the predicted meshes 90 degrees around y-axis and renders it as shown below. 

![screenshot_3](https://user-images.githubusercontent.com/6137870/71250497-1830d300-2320-11ea-8afc-60278af99a20.png)


If you want to view from a different angle, you may modify this line: https://github.com/mkocabas/VIBE/blob/1db923a4f2cd9473377fec2605ec0b2b6e6c85db/demo.py#L301
