### ISSUE TITLE
Add the dataset files

### ISSUE THREAD

**Issue by choward232** [mkocabas/VIBE#80]
Given the eval script, it would be nice if the repo came with the dataset files required to run these scripts. In my case, the script keeps failing because 'data/vibe_db/...' doesn't exist (either mpii3d_val_db.pt or 3dpw_test_db.pt). Thanks!

**Comment by mkocabas** [comment]
Hi @choward232,

Unfortunately it is not possible to share preprocessed data files due to redistribution terms of each dataset. We have already provided the scripts and instructions to obtain them after you download each dataset. Please refer to README.

**Comment by choward232** [comment]
Great, thanks for the quick response
