### ISSUE TITLE
SMPLify during VIBE training

### ISSUE THREAD

**Issue by ikvision** [mkocabas/VIBE#82]
I love your work @mkocabas, its contribution to 3d pose in the wild is impressive, I am trying to understand the major factor contributing to its success.

In the VIBE code --run_smplify is only enabled during **inference**. Are the SOTA kpi [PA-MPJPE](https://paperswithcode.com/sota/3d-human-pose-estimation-on-3dpw?p=vibe-video-inference-for-human-body-pose-and) using this flag?
In SPIN code --run_smplify during **training**, or a preprocessing step generating pseudo ground truth, was the major contributor to the improved results in frame-base setting. 
Did VIBE stopped using SMPLify during training due to its negligible contribution to performance or due to extremely long train time?

Thank you for sharing your work

**Comment by athn-nik** [comment]
Hi @ikvision.
No, the SOTA results did not use that flag.

We use the pretrained SPIN features on the generator part. It did not improve the results and in the same time it did take a lot to train it.
