### ISSUE TITLE
[BUG]Training getting killed

### ISSUE THREAD

**Issue by Liuxinyue521** [mkocabas/VIBE#83]
Hi, here is some configuration of my machine:
Operating System: Ubuntu 18.04
Python: 3.7.5
Pytorch version: torch==1.4.0, torchvision==0.5.0, torchgeometry==0.1.2
After processing all the datasets, I try to run the train command, but it ends with Killed error again..
Here are some outputs:
![image](https://user-images.githubusercontent.com/57157406/82539749-89e7a400-9b80-11ea-89f4-0244a20d228b.png)
Output of nvidia-smi:
![image](https://user-images.githubusercontent.com/57157406/82539804-a1269180-9b80-11ea-8242-2bb1cff87bd2.png)
Output of running dmesg -T| grep -E -i -B100 'killed process':
![image](https://user-images.githubusercontent.com/57157406/82539888-c2877d80-9b80-11ea-878c-f810ddb0cf0f.png)
By the way, I have already tried batch_size=4 and NUM_WORKERS=0 and 1, still get killed. I will appreciate it if anyone can give some advice. Thanks in advance.

**Comment by Liuxinyue521** [comment]
Solved by increasing RAM of the machine

**Comment by asmita005** [comment]
@Liuxinyue521 Could you please tell how much RAM you were using initially when the error occurred and how much you increased for successful training ? Thanks.

**Comment by Z-Z-J** [comment]
Could you please tell how much RAM you were using initially when the error occurred and how much you increased for successful training ? Thanks.

**Comment by liangwx** [comment]
@Z-Z-J @Liuxinyue521 @asmita005 @bvoq @oli4jansen Could you please tell how much RAM you were using initially when the error occurred and how much you increased for successful training ? Thanks.
