### ISSUE TITLE
Mirroring of output data in pickle file [BUG]

### ISSUE THREAD

**Issue by KevGildea** [mkocabas/VIBE#84]
Hi @mkocabas ,

Thank you for this work, it is very impressive!

As I am a windows user, I have been working with the google colab demo notebook.

I have noticed a peculiarity with the .pkl output. I have extracted 3D joint positions and vertices and plotted them in python, and they seem to be mirrored when compared to the generated video from the colab notebook.

Have you any insights as to why this is the case?

**Generated video from colab:**
![image](https://user-images.githubusercontent.com/59794119/82659916-57da4e80-9c21-11ea-917d-97d55d1b3a8f.png)

**From .pkl output:**
![image](https://user-images.githubusercontent.com/59794119/82660013-79d3d100-9c21-11ea-8f7d-c7f3f8fd2b38.png)

**Comment by athn-nik** [comment]
Hey @KevGildea from what I see the one is the frontal view and the other the side view. To me they seem the same mesh can you try plotting them from the same viewpoint.

**Comment by KevGildea** [comment]
Hi @athn-nik, thanks for getting back to me.
So If you look at the shape on the right side of the from colab output video, this viewpoint does in fact correspond to the viewpoint in the plots in the .pkl output shown below. 

I've explored the output in 3D and time and the problem is clear. Here is a gif with an extra viewpoint that might clear it up:
![Extra viewpoints](https://user-images.githubusercontent.com/59794119/82808848-b94d2800-9e82-11ea-9d9f-4343cf49c900.gif)

**Comment by athn-nik** [comment]
Hey @KevGildea, can you provide us with a more clear example of the mirroring issue with another video?It would be better if you provide us with a video without right left symmetry
Thanks

**Comment by mkocabas** [comment]
Closing the issue due to inactivity, feel free to reopen it if needed.
