### ISSUE TITLE
2D keypoint loss is serviously shaking.

### ISSUE THREAD

**Issue by shyanguan** [mkocabas/VIBE#89]
Hi @mkocabas, Thanks for your work. I have pre-processed all datasets except for Human 3.6M. But I observed the tensorboard and found that the 2D keypoint loss is too shaking. I wonder if it's normal?  
![Screenshot from 2020-06-08 14-17-46](https://user-images.githubusercontent.com/22917058/83998720-c6463d00-a993-11ea-9e3c-452a020faf4f.png)

**Comment by mkocabas** [comment]
Hi @shyanguan,

It seems to be fluctuating more than what I observed. There might be an issue with your setup.

**Comment by shyanguan** [comment]
Hi @mkocabas, thanks for your reply. I have another question. In the paper, Human 3.6M and Kinetics-400 are used for training. But you don't use them in your released code. I wonder how big the difference it brings in?

**Comment by athn-nik** [comment]
Human3.6M didn't have any effect on 3DPW performance, but only on its own evaluation subset. About Kinetics-400, we can reproduce paper results without using it.
