### ISSUE TITLE
pyrender error

### ISSUE THREAD

**Issue by antoniolq** [mkocabas/VIBE#9]
Hi, here is my problem, when I run "python demo.py ...."，it shows something in this picture:
![image](https://user-images.githubusercontent.com/23496221/71320000-6260b280-24e0-11ea-83bf-7f76fb1596f8.png)
can you help me? I doubt something wrong with pyrender version?

**Comment by mkocabas** [comment]
Can you try to run this [example](https://colab.research.google.com/drive/1rTLHk0qxh4dn8KNe-mCnN8HAWdd2_BEh) on your computer?

**Comment by antoniolq** [comment]
yeah,  it works online. But it doesn't work in my computer.

**Comment by mkocabas** [comment]
Then, issue is related to pyrender installation. Please refer to pyrender documentation or issues on their github page.
