### ISSUE TITLE
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

### ISSUE THREAD

**Issue by dotieuthien** [mkocabas/VIBE#91]
![image](https://user-images.githubusercontent.com/30580619/84419911-7beae780-ac43-11ea-83b1-d3c87d648858.png)
Plz, Can you give me the way to fix this error when testing demo on sample_video

**Comment by finalspy** [comment]
try downgrading llvmlite to 0.32.1 
` pip install -U llvmlite==0.32.1`

**Comment by athn-nik** [comment]
Seems like the issue is resolved.
