### ISSUE TITLE
Relation between joints of get_smpl_joint_names and get_spin_joint_names

### ISSUE THREAD

**Issue by fryegg** [mkocabas/VIBE#92]
Hi, I'm doing a project that converts a video to a blender animation video. I need joints of get_spin_joint_names (Function from lib/data_utils/kp_utils.py). However, as I know, the demo offers joints of get_spin_joint_names. Thus, I want to know the relation between joints of get_smpl_joint_names and get_spin_joint_names. Or just know how to get 3d joints in a get_smpl_joint_names way. Is anyone who knows the solution?

**Comment by mkocabas** [comment]
Hi @fryegg,

SPIN and SMPL joint definitions are different. `get_smpl_joint_names` indicates the original 24 joints of the SMPL body model. `get_spin_joint_names`, however, is a combination of openpose keypoints and a joint regressor trained to match Human3.6M dataset joint definitions.

To be able to get SMPL joints you need to add these lines after https://github.com/mkocabas/VIBE/blob/master/demo.py#L210:
```
from smplx import SMPL as SMPL_native
from lib.models.smpl import SMPL_MODEL_DIR

smpl_native = SMPL_native(SMPL_MODEL_DIR, batch_size=1, create_transl=False)
native_output = smpl_native(
    betas=pred_betas,
    body_pose=pred_pose[:, 1:],
    global_orient=pred_pose[:, 0].unsqueeze(1),
    pose2rot=False
)
native_smpl_joints = native_output.joints
```

Hope this helps!

**Comment by fryegg** [comment]
`Running "ffmpeg -i /home/choi/webapp/uploads/swang.mp4 -f image2 -v error /tmp/swang_mp4/%06d.png"
Images saved to "/tmp/swang_mp4"
Input video number of frames 138
Running Multi-Person-Tracker
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  4.13it/s]
Finished. Detection + Tracking FPS 34.56
=> loaded pretrained model from 'data/vibe_data/spin_model_checkpoint.pth.tar'
Performance of pretrained model on 3DPW: 56.56075477600098
Loaded pretrained weights from "data/vibe_data/vibe_model_wo_3dpw.pth.tar"
Running VIBE on each tracklet...
  0%|                                                                                                                | 0/1 [00:00<?, ?it/s]cuda

Traceback (most recent call last):
  File "/home/choi/VIBE/demo.py", line 397, in <module>
    main(args)
  File "/home/choi/VIBE/demo.py", line 221, in main
    pose2rot=False,
  File "/home/choi/VIBE/vibe-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/choi/VIBE/vibe-env/lib/python3.7/site-packages/smplx/body_models.py", line 376, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "/home/choi/VIBE/vibe-env/lib/python3.7/site-packages/smplx/lbs.py", line 197, in lbs
    pose_feature = pose[:, 1:].view(batch_size, -1, 3, 3) - ident
RuntimeError: shape '[138, -1, 3, 3]' is invalid for input of size 9798`
I just run the demo.py with adding the code. The result has a reshape problem. When I change pos2rot parameter to 'True', then It works. However, this shape is different with what I guess. I suppose that the result shape is (frame, 24, 3), but It was (frame, 45, 3).

**Comment by j-void** [comment]
Any update regarding the same I am also facing this issue as mentioned in https://github.com/mkocabas/VIBE/issues/92#issuecomment-646061490

**Comment by mkocabas** [comment]
@fryegg, the original SMPL gives 45 joints which are 24 original SMPL joints + 21 joints compatible with 2D keypoint datasets. Refer to this issue from the original smplx package: https://github.com/vchoutas/smplx/issues/18 for more details. So you need to take the first 24 keypoints via `joints[:, :24, :]`.
