### ISSUE TITLE
Unable to prepare training data

### ISSUE THREAD

**Issue by ehedlin** [mkocabas/VIBE#95]
I'm having problems running "source scripts/prepare_training_data.sh" in order to prepare datasets from training/eval. I have gotten the demo working perfectly but for some reason I am getting a suite of errors whenever I run this script. 

Operating system: Ubuntu 18.04.4
python version: 3.7.3

Here is the output when I run "source scripts/prepare_training_data.sh":
[error_message.txt](https://github.com/mkocabas/VIBE/files/4847576/error_message.txt)

**Comment by mkocabas** [comment]
It seems like the error is caused by InstaVariety, I would suggest you to download the dataset file we already provided [here](https://github.com/mkocabas/VIBE/blob/master/doc/train.md#datasets). Also, ACCAD sequence from AMASS seems missing. You need to download it from AMASS website.

**Comment by grau4** [comment]
Hi @mkocabas , thank you for making your excellent work available.

Is there a "prepare_training_data" for windows? Or a hack to run that sh from the VIBE environment?  I followed the windows installation, but it doesn't include data preparation scripts for windows :(

Thank you!
