### ISSUE TITLE
How to get 2D keypoints of feet from VIBE?

### ISSUE THREAD

**Issue by cbsudux** [mkocabas/VIBE#96]
The STAF pose tracker only has a BODY21A model that doesn't have feet keypoints - heel, big toe, small toe that's there in the SMPL model and the  joints3d output.  How do I get the 2D keypoints (relative to image coordinates)?

**Comment by ikvision** [comment]
For 2d keypoints **direct prediction** that includes heel, big toe, small toe - SPIN uses open pose pre-trained https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md#generate-dataset-files 
If your goal is to access the **SMPL reprojected 2d** heel, big toe and small toe position this figure show the j_regressor output 
https://github.com/ikvision/ikvision.github.io/blob/master/README.md#6-transformed-pose-3d-joint-regression
Applying orig_camera on pred_joints3d will generate 2d keypoints in the image coordinates
https://github.com/mkocabas/VIBE/blob/55cf6d606290f0a66554597cc6c0a164d50147a7/demo.py#L218
3d to 2d joint reprojection is done in the training code
https://github.com/mkocabas/VIBE/blob/2ba005c0f2d5e42c15bc8057ab7ad5584192d717/lib/smplify/losses.py#L119-L120

**Comment by cbsudux** [comment]
Okay thanks. @ikvision What do I pass for 1 `rotation, camera_t, focal_length and camera_center` ?

**Comment by ikvision** [comment]
1. I don't think you need to change those in 
https://github.com/mkocabas/VIBE/blob/945fd109eaace037b38c56e22ec235a9d3c5100a/lib/models/spin.py#L427-L429
2. To convert from cropped camera to original camera - in the original image resolution
https://github.com/mkocabas/VIBE/blob/3e04e0fbc157d5606111c9bba74e6ef55bb68b37/demo.py#L219-L223

Can you post the output 2d pose image you get in the cropped coordinate system and in the original image resolution to understand the gap you are facing

**Comment by cbsudux** [comment]
I actually haven't run it yet. For the pred_cam in cropped image space you have the below code where you take `tx` and `ty` and add the third dimension as this `2 * 5000. / (224. * pred_camera[:, 0] + 1e-9)]` where `244` is the crop size. 

https://github.com/mkocabas/VIBE/blob/945fd109eaace037b38c56e22ec235a9d3c5100a/lib/models/spin.py#L427-L429

1) How do I adapt it `2 * 5000. / (224. * pred_camera[:, 0] + 1e-9)]` to the full image where width and height are different? 
2)  What exactly does this line mean `2 * 5000. / (224. * pred_camera[:, 0] + 1e-9)]`?
3) Are `sx, sy` which are part of `orig_cam` not used in transformation?

**Comment by cbsudux** [comment]
In a simpler form, given `orig_cam = (sx, sy, tx, ty)` and `joints_3d` how do I get 2D keypoints wrt the original image?

**Comment by cbsudux** [comment]
In a simpler form, given orig_cam = (sx, sy, tx, ty) and joints_3d how do I get 2D keypoints wrt the original image?

**Comment by mkocabas** [comment]
I am closing this issue for now, we can continue the discussion in issue https://github.com/mkocabas/VIBE/issues/100
